[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "barcode-changer"
version = "0.1.7"
description = "CLI tool to read and change barcodes in image pairs from an input/ folder"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "opencv-python",
  "numpy",
  "huggingface_hub",
  "ultralytics",
  "rawpy",
  "imageio",
  "zxing-cpp==2.3.0",
  "pyrxing",
]

[project.scripts]
barcode-changer = "barcode_changer_tool.barcode_changer:main"
[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["barcode_changer_tool*", "barcode_reader*"]
